name: KotlinPlugins
version: '1.0-SNAPSHOT'
main: winlyps.kotlinPlugins.KotlinPlugins
api-version: '1.16'
authors: [ Winlyps ]
commands:
  kotlinplugins:
    description: Lists plugins using by looking for Kotlin modules.
    usage: /kotlinplugins
    permission: kotlinplugins.use
permissions:
  kotlinplugins.use:
    default: op